# Site settings
title: "Greg & Laura's Wedding"
email: rsvp@newshineyweddingdomain.com
description: All the details for Greg @ Laura's wedding at Larmer Tree Gardens on 28 May 2016!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://newshineyweddingdomain.com" # the base hostname & protocol for your site

# Build settings
source: source
destination: build
markdown: kramdown
