# Site settings
title: "Mr & Mrs Hepworth"
email: rsvp@mrandmrshepworth.com
description: "All the details for Greg & Laura's wedding at Larmer Tree Gardens on 28 May 2016!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mrandmrshepworth.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [vendor, Gemfile, Gemfile.lock, README.md, CNAME]
